#!/usr/bin/env python3
"""Generate CityU and HKJC FAQ files."""
import os

BASE = 'FAQ_test'

cityu = [
    ('CityU-ProSmartService/供应商管理','EP23CITYU-528','Browser Autofill Overwrites Contract Sum Field with User ID','Supplier Form',['faq','CityU','bug'],'Browser auto-fills Total Contract Sum field with User ID instead of contract sum','Browser autofill/saved form data interfering with input field','Set autocomplete=off on field; clear browser cache','2026-01-23',''),
    ('CityU-ProSmartService/供应商管理','EP23CITYU-510','System Error When Clicking Supplier Profile','Supplier Profile',['faq','CityU','bug'],'System error clicking Supplier Profile on Procurer portal','Field mobile_no_area_code contained CHI not in dropdown','Added CHI to area code dropdown','2025-02-24',''),
    ('CityU-ProSmartService/供应商管理','EP23CITYU-499','Supplier Profile Updated After Reviewer Rejection','Supplier Profile',['faq','CityU','bug'],'Profile updated even after reviewer rejected application','Missing approval status check on save operation','Added approval check before allowing updates','2024-12-05',''),
    ('CityU-ProSmartService/供应商管理','EP23CITYU-405','Duplicate BR/PRC Number Only Detected at Approver Step','Supplier Registration',['faq','CityU','bug'],'Duplicate BR/PRC validation only triggers at approver, not at save','Validation only applied during approval, not initial save','Added duplicate BR/PRC validation at save stage','2024-03-19',''),
    ('CityU-ProSmartService/供应商管理','EP23CITYU-418','Email Duplication Check Flags Own Email as Duplicate','Supplier Info',['faq','CityU','bug'],'Email check flags supplier own email as duplicate','Validation compares all emails including supplier own current email','Exclude current supplier own email from check','2024-03-21',''),
    ('CityU-ProSmartService/供应商管理','EP23CITYU-492','Recommended Supplier Cannot Be Found in Invitation List','Supplier Mgmt',['faq','CityU','bug'],'User-recommended supplier not in list','Commodity code removed from one table while data in another','SQL data sync between tables','2024-10-15',''),
    ('CityU-ProSmartService/供应商管理','EP23CITYU-493','False Duplicate Email Error (Purged Supplier Data)','Supplier Mgmt',['faq','CityU','bug'],'False duplicate email when changing company name','Validation checked against purged supplier data','Exclude purged suppliers from duplicate check','2024-10-15',''),
    ('CityU-ProSmartService/供应商管理','EP23CITYU-452','Cannot Send Invitation Due to Cached Old Email','Supplier Invitation',['faq','CityU','bug'],'After changing email, old email still shows and blocks invitation','System cached old email, not clearing on update','Code fix deployed to production 2024-07-10','2024-07-10',''),
    ('CityU-ProSmartService/供应商管理','EP23CITYU-462','Rejected Supplier Records Still Synced to Oracle EBS','Supplier Sync',['faq','CityU','bug'],'Rejected records still synced to Oracle','date_modified updated even when rejected, triggering sync','Do not update date_modified when rejected','2024-09-19',''),
    ('CityU-ProSmartService/邀请与开标','EP23CITYU-295','Invitation Record Missing After Send (Duplicate Phone)','Supplier Invitation',['faq','CityU','bug'],'Invitation missing after send with no error','Duplicate phone caused silent failure','Fixed error handling for duplicate phone','2023-10-20',''),
    ('CityU-ProSmartService/邀请与开标','EP23CITYU-489','All Suppliers Disappear After Removing Selected','Invitation List',['faq','CityU','bug'],'All suppliers disappear after removing selected ones and saving','Save cleared entire list instead of only selected','Fix deployed to UAT and PRD','2024-09-30',''),
    ('CityU-ProSmartService/邀请与开标','EP23CITYU-507','Manual Supplier in Opening Appears in Contract Award','Contract Award',['faq','CityU','bug'],'Manual supplier in Opening Form appears in Contract Award','System pulled data from Opening into Contract Award without filter','Exclude non-bidding suppliers from Contract Award','2025-02-13',''),
    ('CityU-ProSmartService/文件与下载','EP23CITYU-514','Pricing Proposal File Damaged (Double Decryption)','Document',['faq','CityU','bug'],'File damaged when opening Pricing Proposal for hybrid RFQ','Double decryption due to hybrid RFQ logic','Fixed decryption to run only once','2025-05-09',''),
    ('CityU-ProSmartService/文件与下载','EP23CITYU-433','404 Error Downloading Letter Q and A','Submission Log',['faq','CityU','bug'],'404 error downloading Letter Q&A','Download denied before Price Opening sign-off','Allow download when button visible','2024-04-10',''),
    ('CityU-ProSmartService/文件与下载','EP23CITYU-439','Letter Q and A Files in Zipped Q and A Download','Opening Record',['faq','CityU','bug'],'Letter Q&A files in zipped Q&A download','Download logic did not filter Letter Q&A','Filter Letter Q&A from regular Q&A download','2024-04-09',''),
    ('CityU-ProSmartService/文件与下载','EP23CITYU-441','Empty Folder for Offline Supplier Download','Opening Record',['faq','CityU','bug'],'Empty folder for offline submission download','System creates folders even with no files','Do not show empty folders; mark as Submission (New)','2024-04-10',''),
    ('CityU-ProSmartService/DOI与技术评估','EP23CITYU-513','DOI Error After DOI Started (Buyer as Assessor)','EOI/DOI',['faq','CityU','bug'],'Supplier gets DOI error after DOI started','Buyer assigned as assessor creates conflict','Buyers should not be assessors in own RFQ','2025-05-07',''),
    ('CityU-ProSmartService/DOI与技术评估','EP23CITYU-466','Approver Asked to Submit DOI for Proposals','DOI/Proposal',['faq','CityU','bug'],'Approver incorrectly asked to submit DOI','System incorrectly requires DOI from approvers','Fix deployed to UAT55 then PRD','2024-09-19',''),
    ('CityU-ProSmartService/DOI与技术评估','EP23CITYU-392','Assessor Cannot Download After DOI Endorsement','DOI/Tech Assessment',['faq','CityU','bug'],'Technical assessor cannot see download button after DOI endorsement','DB record mismatch between DOI Control and DOI Submission tables','DB fix to sync both tables','2024-07-22',''),
    ('CityU-ProSmartService/系统错误','EP23CITYU-448','date_modified Not Updated on Contact Info Change','Supplier DB Sync',['faq','CityU','bug'],'date_modified not updated when contact info changes','Missing trigger on date_modified for supplier user changes','Fix Patch deployed to Production','2024-06-28',''),
    ('CityU-ProSmartService/系统错误','EP23CITYU-450','Yellow Page Error on Request Task (Empty vs Numeric)','Procurer Portal',['faq','CityU','bug'],'Yellow page error clicking Request Task','Program checked for number but DB had empty string','Fix Patch deployed 2024-07-08','2024-07-08',''),
    ('CityU-ProSmartService/系统错误','EP23CITYU-457','Yellow Page Error on Edit Recommendation','Recommendation',['faq','CityU','bug'],'Yellow page error on Edit Recommendation','DB field had empty string instead of number','Fix deployed by Lucky_Huang 2024-07-31','2024-08-01',''),
    ('CityU-ProSmartService/系统错误','EP23CITYU-455','Purged Supplier Blocks New Invitation','Supplier Mgmt',['faq','CityU','bug'],'Cannot send invitation due to purged supplier duplicate check','Duplicate check compared against purged data','Bypass purged suppliers in validation','2024-07-26',''),
]

hkjc = [
    ('HKJC-ProSmart/RFQ','EP21HKJC-3967','Number of Submitted Quotes Displays Incorrectly','RFQ',['faq','HKJC','bug'],'Number of submitted quotes shows wrong count','Counting logic error','Fix deployed by Aaron_So','2024-09-02',''),
    ('HKJC-ProSmart/RFQ','EP21HKJC-3978','Number of Tenders Received Shows Incorrect Count','RFQ',['faq','HKJC','bug'],'Number of tenders received is incorrect','Counting logic did not exclude no-response/no-offer','Fix deployed by Aaron_So','2024-08-16',''),
    ('HKJC-ProSmart/RFQ','EP21HKJC-2014','Bidders Not Shown After Post-RFQ Clarification','RFQ',['faq','HKJC','bug'],'Bidders not shown after Post-RFQ Clarification','PTA/PTC did not inherit invitation list from parent RFX','Fixed and datapatch applied','2024-08-08',''),
    ('HKJC-ProSmart/RFQ','EP21HKJC-2005','Download Returns HTTP 404 in RFQ','RFQ',['faq','HKJC','bug'],'Clicking download returns HTTP 404','Fixed by Aaron_So; only works on future submissions','Fixed','2024-08-08',''),
    ('HKJC-ProSmart/RFQ','EP21HKJC-1958','Endorsement Shows Technical Assessment in Price-Only Flow','RFQ',['faq','HKJC','bug'],'Endorsement shows technical assessment text in price-only flow','UI logic did not differentiate flow types','Conditional text display based on flow type','2023-04-03',''),
    ('HKJC-ProSmart/RFQ','EP21HKJC-1903','Bidder Names Visible After Hide in Assessment Results','RFQ',['faq','HKJC','bug'],'Bidder names visible after selecting Hide','Hide option not properly implemented','Fixed','2023-04-12',''),
    ('HKJC-ProSmart/RFQ','EP21HKJC-1957','View Button Shows Not Authorized in Price Opening','RFQ',['faq','HKJC','bug'],'View button shows Not Authorized in Price Opening','Fix applied','Fixed','2023-04-25',''),
    ('HKJC-ProSmart/RFQ','EP21HKJC-1456','Approver Task Missing BOQ Record Section','RFQ/RFT',['faq','HKJC','bug'],'Approver task missing BOQ record','Code not deployed to UAT8','Deployed fix','2023-04-28',''),
    ('HKJC-ProSmart/RFQ','EP21HKJC-1896','BOQ Supplier Unknown Error on Validate Folder','RFQ',['faq','HKJC','bug'],'Unknown error when Validate Folder in BOQ','Fixed','Fixed (High priority)','2023-02-17',''),
    ('HKJC-ProSmart/RFQ','EP21HKJC-1892','BOQ Supplier Missing PTA Option in Dropdown','RFQ',['faq','HKJC','bug'],'BOQ Supplier Verification missing PTA option','Fixed','Fixed (High priority)','2023-02-17',''),
    ('HKJC-ProSmart/RFQ','EP21HKJC-1996','Trustee Cannot Perform Bidder List Approval','RFQ',['faq','HKJC','bug'],'Trustee cannot perform Bidder List Approval','Fixed by Aaron_So','Fixed','2023-07-24',''),
    ('HKJC-ProSmart/RFQ','EP21HKJC-1416','Server Error Creating E-Form Supplier Account','RFT',['faq','HKJC','bug'],'Server error creating e-form supplier account','Fixed by Joseph_Hu','Fixed','2023-01-12',''),
    ('HKJC-ProSmart/RFQ','EP21HKJC-1085','No Bidders Can Be Selected in RFQ PTC','RFQ',['faq','HKJC','bug'],'Bidder list empty in RFQ PTC','Bug in PTC bidder retrieval','Fixed in UAT8 by Steve_Wong','2023-01-01',''),
    ('HKJC-ProSmart/RFQ','EP21HKJC-3738','Upload Buttons Wrong in Commercial PTC for Item-Based RFQ','RFQ',['faq','HKJC','bug'],'Upload buttons appear in wrong PTC section','UI visibility logic did not differentiate Technical vs Commercial PTC','Fixed by Aaron_So','2024-08-08',''),
    ('HKJC-ProSmart/RFQ','EP21HKJC-1855','Submit RFQ Queries Button Has No Reaction','RFQ',['faq','HKJC','bug'],'Submit RFQ Queries button produces no reaction','Code issue with submission','Tested and fixed by Steve_Wong','2023-01-29',''),
    ('HKJC-ProSmart/RFQ','EP21HKJC-972','Clean Version Not Removed When Switching to Original','RFQ/RFT',['faq','HKJC','bug'],'Switching to original does not remove clean version','Save logic does not remove clean version','', '2023-01-01',''),
    ('HKJC-ProSmart/RFQ','EP21HKJC-1916','RFQ Price Detail Fields Go Blank After Edit Save','RFQ',['faq','HKJC','bug'],'Price detail fields blank after editing and saving','Bug in price detail save logic causing field loss','Fixed price detail save logic','2023-01-01',''),
    ('HKJC-ProSmart/RFQ','EP21HKJC-865','Tabs Disappear After Rejecting Late Quote','RFQ',['faq','HKJC','bug'],'Tech/Commercial tabs disappear after rejecting late quote','Reject logic removed valid proposal data','Ensure rejection does not affect existing proposals','2023-01-01',''),
    ('HKJC-ProSmart/RFQ','EP21HKJC-864','Invalid Closing Date When Issue Date Equals Closing Date','RFQ',['faq','HKJC','bug'],'Invalid closing date error when issue date equals closing date','Validation incorrectly rejects same-day issue and closing','Allow issue date to equal closing date','2023-01-01',''),
    ('HKJC-ProSmart/RFQ','EP21HKJC-856','Pass/Fail Count Shows Wrong Total in Opening Results','RFQ',['faq','HKJC','bug'],'Pass/fail count shows wrong total','Rejected late quotes counted in denominator','Exclude rejected late quotes from total','2023-01-01',''),
    ('HKJC-ProSmart/RFQ','EP21HKJC-845','Request Approval Bidder List Stuck on Processing','RFQ',['faq','HKJC','bug'],'Bidder list approval stuck on processing','Backend processing issue','Fixed approval processing logic','2023-01-01',''),
    ('HKJC-ProSmart/RFQ','EP21HKJC-782','Invalid File Upload Shows Object HTMLInputElement Error','RFQ',['faq','HKJC','bug'],'Error shows [object HTMLInputElement] on invalid file','JavaScript displaying HTML element instead of text','Fixed error message to show correct text','2023-01-01',''),
    ('HKJC-ProSmart/RFQ','EP21HKJC-969','Cannot Lock Bid Submission After Inviting Supplier','RFQ',['faq','HKJC','bug'],'Cannot lock bid/tender submission after inviting supplier','Workflow state issue','Fixed locking mechanism','2023-01-01',''),
    ('HKJC-ProSmart/RFQ','EP21HKJC-1057','Filtered Supplier Search Results Not Saved on Click','RFQ/RFT',['faq','HKJC','bug'],'Selected suppliers from filter search not saved','Search/filter save mechanism did not persist selections','Fixed filter search save functionality','2023-01-01',''),
    ('HKJC-ProSmart/RFQ','EP21HKJC-1683','Download Link in Opening Task Goes to Wrong Page','RFQ',['faq','HKJC','bug'],'Download link in opening task goes to wrong page','Download URL/endpoint broken','Fixed download link','2023-01-01',''),
    ('HKJC-ProSmart/RFQ','EP21HKJC-935','Supplier Stuck on Processing After Issuing RFQ/RFT','RFQ',['faq','HKJC','bug'],'Supplier stuck on processing when submitting after issuance','Backend processing issue','Fixed supplier submission processing','2023-01-01',''),
    ('HKJC-ProSmart/RFQ','EP21HKJC-1853','Submit RFQ Queries Button Has No Action','RFQ',['faq','HKJC','bug'],'Submit RFQ queries button no action','RFQ with BOQ in wrong test plan','Tested and fixed by Steve_Wong','2023-01-29',''),
    ('HKJC-ProSmart/RFQ','EP21HKJC-1682','Bidder Section Empty in Issue PTC Page','RFQ',['faq','HKJC','bug'],'Bidder section empty in Issue PTC','Fixed in UAT8 by Steve_Wong','Fixed','2023-01-01',''),
    ('HKJC-ProSmart/RFT','EP21HKJC-3976','Terms and Conditions Missing in e-CLM Report','RFT',['faq','HKJC','bug'],'Terms and conditions missing in e-CLM report','Data rendering issue','Fix deployed by Aaron_So','2024-08-20',''),
    ('HKJC-ProSmart/RFT','EP21HKJC-2081','No Input Field for Total Tender Price','RFT',['faq','HKJC','bug'],'No input field for Total Tender Price','Code sync problem','Fixed by Aaron_So','2024-08-08',''),
    ('HKJC-ProSmart/RFT','EP21HKJC-1925','Missing Email Notifications for PTA/PTC/PTN','RFT',['faq','HKJC','bug'],'Missing email notifications for PTA/PTC/PTN and closing changes','Missing email triggers','Email triggers implemented','2024-08-08',''),
    ('HKJC-ProSmart/RFT','EP21HKJC-1960','Commercial Eval Shows Dash Instead of Done in Negotiation','RFT',['faq','HKJC','bug'],'Commercial eval shows -- instead of done in Negotiation','Fixed by Aaron_So','Fixed','2023-03-29',''),
    ('HKJC-ProSmart/RFT','EP21HKJC-1913','PTC Can Be Submitted Without Selecting Suppliers','RFT',['faq','HKJC','bug'],'PTC submitted without selecting suppliers','Missing validation','Blocking validation added','2023-02-14',''),
    ('HKJC-ProSmart/RFT','EP21HKJC-1865','Return to Assessor Does Not Update Total Result','EOI',['faq','HKJC','bug'],'Total Result not updated after Return to Assessor','Fixed by Steve_Wong','Fixed in UAT8','2023-02-17',''),
    ('HKJC-ProSmart/RFT','EP21HKJC-1423','Edit Tenderers Shows No Tenderers in PTC','RFT',['faq','HKJC','bug'],'Edit Tenderers in PTC shows no tenderers','Fixed by Steve_Wong','Fixed in UAT8','2023-01-16',''),
    ('HKJC-ProSmart/RFT','EP21HKJC-1859','Endorsement Overall Results Only Shows Price Assessor','RFT',['faq','HKJC','bug'],'Endorsement only shows Price Assessor','Fixed','Fixed (Highest priority)','2023-01-30',''),
    ('HKJC-ProSmart/RFT','EP21HKJC-1852','500 Error Getting OTP When Responding to PTN','RFT',['faq','HKJC','bug'],'500 error getting OTP for PTN response','Fixed by Steve_Wong','Fixed','2023-01-29',''),
    ('HKJC-ProSmart/RFT','EP21HKJC-1021','Supplier Gets 500 Error on Request OTP','RFT',['faq','HKJC','bug'],'500 error when supplier requests OTP for submit','Could not reproduce; possibly already fixed','Fixed','2023-01-01',''),
    ('HKJC-ProSmart/RFT','EP21HKJC-1930','Missing Assessor Error on Commercial Evaluation','RFT',['faq','HKJC','bug'],'Missing assessor error on commercial eval in Price-Only RFT','Approval type configuration issue','Fixed in UAT8','2023-03-01',''),
    ('HKJC-ProSmart/RFT','EP21HKJC-1411','External Assessor Cannot Update Endorse Results','RFQ/RFT',['faq','HKJC','bug'],'External assessor cannot update endorse results','Restriction limited to Technical Evaluation stage only','Removed restriction by Steve_Wong','2023-01-01',''),
    ('HKJC-ProSmart/RFT','EP21HKJC-1430','Price Assessor Server Error on Download Button','RFT',['faq','HKJC','bug'],'Server error on download button for Price Assessor','Bug in assessor download','Fixed in UAT8 by Steve_Wong','2023-01-16',''),
    ('HKJC-ProSmart/RFT','EP21HKJC-832','Cannot Lock Bid Submission for Opening','RFT',['faq','HKJC','bug'],'Cannot lock bid submission and proceed to opening','Workflow state transition issue','Fixed workflow logic','2023-01-01',''),
    ('HKJC-ProSmart/RFT','EP21HKJC-2059','Technical Assessor List Missing in Tender Issuance Approval','RFQ/RFT',['faq','HKJC','bug'],'Technical assessor list missing in issuance approval','Assessor data not passed to approval flow','Ensure assessor list loads during approval','2024-08-08',''),
    ('HKJC-ProSmart/RFT','EP21HKJC-1045','Cannot Change Closing Date/Time After Setting','RFT',['faq','HKJC','bug'],'Cannot change closing date/time after setting','Update logic prevented modification','Fixed closing date/time change','2023-01-01',''),
    ('HKJC-ProSmart/RFT','EP21HKJC-1444','RFT Technical Assessment Pass/Fail Count Wrong','RFQ/RFT',['faq','HKJC','bug'],'Technical assessment pass/fail count wrong','Denominator includes excluded suppliers','Fixed denominator calculation','2023-01-01',''),
    ('HKJC-ProSmart/BOQ','EP21HKJC-1944','Combine BOQ Button Error with SGD Currency','BOQ',['faq','HKJC','bug'],'Combine BOQ button error with SGD; Column AP missing','Dropdown allowed text input + SGD had no rate record','Changed to dropdown list + added currency record','2023-03-01',''),
    ('HKJC-ProSmart/BOQ','EP21HKJC-1935','BOQ Analysis Report Wrong Data for Non-HKD Currencies','BOQ',['faq','HKJC','bug'],'BOQ converts non-HKD amounts but labels not updated','Currency conversion not comprehensive across templates','All templates updated','2023-03-01',''),
    ('HKJC-ProSmart/BOQ','EP21HKJC-1017','BOQ No Warning When Folder Ref Mismatches','BOQ',['faq','HKJC','bug'],'BOQ Supplier does not validate Ref number consistency','Missing validation logic','Show mismatch error','2023-02-13',''),
    ('HKJC-ProSmart/BOQ','EP21HKJC-1007','Excel Version Mismatch Error on BOQ Folder Validation','BOQ',['faq','HKJC','bug'],'Excel version mismatch error on BOQ folder validation','System incorrectly rejected valid Excel files','Fixed Excel version check','2023-01-01',''),
    ('HKJC-ProSmart/BOQ','EP21HKJC-1009','File Count Mismatch Error on BOQ Folder Validation','BOQ',['faq','HKJC','bug'],'File count mismatch error on BOQ folder validation','File count validation incorrect','Fixed file count validation','2023-01-01',''),
    ('HKJC-ProSmart/BOQ','EP21HKJC-1871','BOQ Analysis Report Throws ArgumentException on Login','BOQ',['faq','HKJC','bug'],'BOQ Analysis Report throws ArgumentException on login','Not documented','Not documented','2023-02-17',''),
    ('HKJC-ProSmart/BOQ','EP21HKJC-1486','BOQ Supplier Input Shows Empty Cells in Export','BOQ',['faq','HKJC','bug'],'Supplier BOQ input shows empty cells in export','Not documented','Not documented','2023-01-01',''),
    ('HKJC-ProSmart/大文件上传','EP21HKJC-914','Files Stay Pending in LargeFile Uploader After SYNC','LargeFile',['faq','HKJC','bug'],'Files remain Pending after SYNC in LargeFile Uploader','Disk full on server; no error shown to user','Freed disk space; suggested disk full message','2024-08-08',''),
    ('HKJC-ProSmart/大文件上传','EP21HKJC-2008','Supplier File Uploads Fail When Submitting Proposal','RFQ/RFT',['faq','HKJC','bug'],'Supplier uploads fail submitting proposal/quotation','Fixed by Aaron_So','Fixed','2024-08-08',''),
    ('HKJC-ProSmart/大文件上传','EP21HKJC-905','Cannot Upload .doc/.xls/.ppt via LargeFile Uploader','RFQ/RFT',['faq','HKJC','bug'],'Cannot upload .doc/.xls/.ppt files','MIME/filter blocked older Office formats','Updated upload validation to allow these extensions','2023-01-01',''),
    ('HKJC-ProSmart/大文件上传','EP21HKJC-1475','Large File Upload Not Available in Addendum Screen','RFQ/RFT',['faq','HKJC','bug'],'Large file upload not in addendum screen','Webservice did not return addendum data to client','Updated webservice by Steve_Wong','2023-01-01',''),
    ('HKJC-ProSmart/大文件上传','EP21HKJC-1509','Large File Upload Shows Generic Error with No Details','LargeFile',['faq','HKJC','bug'],'Large file upload shows generic error, no details','Bug in client program','New client exe provided','2023-01-01',''),
    ('HKJC-ProSmart/大文件上传','EP21HKJC-722','500MB+ Upload Shows Wrong Size (512MB), Back Button Broken','LargeFile',['faq','HKJC','bug'],'Large upload: wrong size limit msg, Back button broken','Size validation inconsistency; no upload progress','Fixed error message, added progress, fixed Back nav','2023-01-01',''),
    ('HKJC-ProSmart/大文件上传','EP21HKJC-721','Large Upload: Same Issues as EP21HKJC-722','LargeFile',['faq','HKJC','bug'],'Same as EP21HKJC-722: size msg, Back button, blank page','Generic upload module issue','Same fix as 722','2023-01-01',''),
    ('HKJC-ProSmart/大文件上传','EP21HKJC-913','Large File Downloader Auto-Exits; Old User Download Path','RFT',['faq','HKJC','bug'],'Downloader auto-exits; shows old user download path','Fixed','Fixed (Highest priority)','2023-01-01',''),
    ('HKJC-ProSmart/大文件上传','EP21HKJC-1894','404 Error Downloading Addendum Files','RFQ',['faq','HKJC','bug'],'404 error downloading addendum files','Developer fix saved files to local PC instead of server','Addendum re-created','2023-02-08',''),
    ('HKJC-ProSmart/EOI-PQ','EP21HKJC-670','Receive Notification Always Shows {2} Regardless of Setting','EOI/PQ',['faq','HKJC','bug'],'Notification display shows {2} not actual setting','Notification preference not read correctly','Fixed notification display','2023-01-01',''),
    ('HKJC-ProSmart/EOI-PQ','EP21HKJC-213','PQ Form: File Types Mismatch, 0kb Size, Empty Upload Field','PQ',['faq','HKJC','bug'],'PQ form: file types mismatch, 0kb, empty upload field','Validation messages/config out of sync','Fixed file type consistency and size display','2023-01-01',''),
    ('HKJC-ProSmart/EOI-PQ','EP21HKJC-708','Old Supplier Values Remain After Dropdown Reset','EOI/LWR',['faq','HKJC','bug'],'Old supplier ID/nature remain when dropdown reset to Select','UI did not clear dependent fields','Clear all dependent fields on reset','2023-01-01',''),
    ('HKJC-ProSmart/系统流程','EP21HKJC-4056','Cannot Open Local Environment Link (Invalid Operation)','System',['faq','HKJC','bug'],'Cannot open local env link; Invalid operation error','Local env configuration issue','Fixed by Aaron_So','2025-03-07',''),
    ('HKJC-ProSmart/系统流程','EP21HKJC-1478','HTTP 404 Error Creating File Record in PTX','PTX',['faq','HKJC','bug'],'404 error creating file record in PTX','Web service endpoint missing or misconfigured','Fixed endpoint','2023-01-01',''),
]

all_entries = [('CityU', cityu), ('HKJC', hkjc)]

for proj, entries in all_entries:
    for cat, jira, title, comp, tags, sym, rc, sol, res, fv in entries:
        d = os.path.join(BASE, cat)
        os.makedirs(d, exist_ok=True)
        slug = f'{jira}-{title.lower().replace(" ","-").replace("/","-")[:60]}'
        fp = os.path.join(d, f'{jira}.md')
        tags_s = ', '.join(tags)
        content = f'---\ntags: [{tags_s}]\ncomponent: "{comp}"\nsymptom: "{sym}"\nroot-cause: "{rc}"\nsolution: "{sol}"\njira: {jira}\nresolved: {res}\nfix-version: "{fv}"\n---\n\n# {jira}: {title}\n\n## 問題\n\n{sym}\n\n## 根因\n\n{rc}\n\n## 解法\n\n{sol}\n\n## 相關資訊\n\n- Jira: [{jira}](https://ctil.atlassian.net/browse/{jira})\n- 解決日期: {res}\n'
        with open(fp, 'w', encoding='utf-8') as f:
            f.write(content)

print(f'CityU: {len(cityu)} files')
print(f'HKJC: {len(hkjc)} files')
print(f'Total: {len(cityu) + len(hkjc)} FAQ files generated')
